export const transactionHistory = [
  {
    status: "Successful",
    type: "Debit",
    createdAt: "15th August 2024",
    time: "10:50 PM",
    merchant: "Playstation Store",
    amount: "10.99 USD",
    description: "PS Plus payment",
  },
  {
    status: "Successful",
    type: "Debit",
    createdAt: "15th August 2024",
    time: "4:12 AM",
    merchant: "Apple Store Purchase",
    amount: "3.99 USD",
    description: "Payment for Call Of Duty purchase",
  },
  {
    status: "Declined",
    type: "Debit",
    createdAt: "15th August 2024",
    time: "4:12 AM",
    merchant: "Amazon Store purchase",
    amount: "3.99 USD",
    description: "Payment for Nike Dunks purchase",
  },
  {
    status: "Successful",
    type: "Debit",
    createdAt: "15th August 2024",
    time: "4:12 AM",
    merchant: "Apple Store Purchase",
    amount: "3.99 USD",
    description: "Payment for Call Of Duty purchase",
  },
  {
    status: "Successful",
    type: "Debit",
    createdAt: "15th August 2024",
    time: "4:12 AM",
    merchant: "Apple Store Purchase",
    amount: "3.99 USD",
    description: "Payment for Call Of Duty purchase",
  },
  {
    status: "Successful",
    type: "Fund",
    createdAt: "1st September 2024",
    time: "10:50 PM",
    merchant: "Damilola Adegbemile",
    amount: "7.99 USD",
    description: "Funded account",
  },
  {
    status: "Successful",
    type: "Debit",
    createdAt: "1st September 2024",
    time: "7:01 PM",
    merchant: "Playstation Store",
    amount: "7.99 USD",
    description: "Purchase",
  },
  {
    status: "Successful",
    type: "Debit",
    createdAt: "1st September 2024",
    time: "10:50 PM",
    merchant: "LinkedIn",
    amount: "7.99 USD",
    description: "Purchase for sales navigator",
  },
  {
    status: "Successful",
    type: "Debit",
    createdAt: "1st September 2024",
    time: "10:50 PM",
    merchant: "Spotify",
    amount: "1.99 USD",
    description: "Monthly subscription",
  },
  {
    status: "Declined",
    type: "Debit",
    createdAt: "1st September 2024",
    time: "10:50 PM",
    merchant: "Apple Music",
    amount: "5.00 USD",
    description: "Monthly subscription",
  },
];
